AWS:
  period: 60
  logmode: debug ## info/debug
    
Metrics:
  DatabaseConnections:
    description: "Database Connections Count"
    type: gauge
  CPUUtilization:
    description: "Database CPUUtilization"
    type: gauge
  FreeableMemory:
    description: "Database FreeableMemory"
    type: gauge
  DMLLatency:
    description: "Database DMLLatency"
    type: gauge
  CommitLatency:
    description: "Database CommitLatency"
    type: gauge
  
## Metrics List
# ActiveTransactions
# AuroraBinlogReplicaLag
# AuroraGlobalDBDataTransferBytes
# AuroraGlobalDBReplicatedWriteIO
# AuroraGlobalDBReplicationLag
# AuroraReplicaLag
# AuroraReplicaLagMaximum
# AuroraReplicaLagMinimum
# AvailabilityPercentage
# BacktrackChangeRecordsCreationRate
# BacktrackChangeRecordsStored
# BacktrackWindowActual
# BacktrackWindowAlert
# BackupRetentionPeriodStorageUsed
# BinLogDiskUsage
# BlockedTransactions
# BufferCacheHitRatio
# BurstBalance
# CPUCreditBalance
# CPUCreditUsage
# CPUUtilization
# ClientConnections
# ClientConnectionsClosed
# ClientConnectionsNoTLS
# ClientConnectionsReceived
# ClientConnectionsSetupFailedAuth
# ClientConnectionsSetupSucceeded
# ClientConnectionsTLS
# CommitLatency
# CommitThroughput
# DDLLatency
# DDLThroughput
# DMLLatency
# DMLThroughput
# DatabaseConnectionRequests
# DatabaseConnectionRequestsWithTLS
# DatabaseConnections
# DatabaseConnectionsBorrowLatency
# DatabaseConnectionsCurrentlyBorrowed
# DatabaseConnectionsCurrentlyInTransaction
# DatabaseConnectionsCurrentlySessionPinned
# DatabaseConnectionsSetupFailed
# DatabaseConnectionsSetupSucceeded
# DatabaseConnectionsWithTLS
# Deadlocks
# DeleteLatency
# DeleteThroughput
# DiskQueueDepth
# EngineUptime
# FailedSQLServerAgentJobsCount
# FreeLocalStorage
# FreeStorageSpace
# FreeableMemory
# InsertLatency
# InsertThroughput
# LoginFailures
# MaxDatabaseConnectionsAllowed
# MaximumUsedTransactionIDs
# NetworkReceiveThroughput
# NetworkThroughput
# NetworkTransmitThroughput
# OldestReplicationSlotLag
# Queries
# QueryDatabaseResponseLatency
# QueryRequests
# QueryRequestsNoTLS
# QueryRequestsTLS
# QueryResponseLatency
# RDSToAuroraPostgreSQLReplicaLag
# ReadIOPS
# ReadLatency
# ReadThroughput
# ReplicaLag
# ReplicationSlotDiskUsage
# ResultSetCacheHitRatio
# SelectLatency
# SelectThroughput
# ServerlessDatabaseCapacity
# SnapshotStorageUsed
# SwapUsage
# TotalBackupStorageBilled
# TransactionLogsDiskUsage
# TransactionLogsGeneration
# UpdateLatency
# UpdateThroughput
# VolumeBytesUsed
# VolumeReadIOPs
# VolumeWriteIOPs
# WriteIOPS
# WriteLatency
# WriteThroughput